/**
 * Each LED can have three states: OFF (OFFFF) , ON (SOLID) , FLASHING (FLASH)
 * Since we have two LEDs, we can have (2^3) =8 different states
 */

enum AdvertisementMode : uint8_t {
  MODE_LEFT_OFFFF_RIGHT_OFFFF = 0,
  MODE_LEFT_OFFFF_RIGHT_FLASH = 1,
  MODE_LEFT_OFFFF_RIGHT_SOLID = 2,
  MODE_LEFT_FLASH_RIGHT_OFFFF = 3,
  MODE_LEFT_FLASH_RIGHT_FLASH = 4,
  MODE_LEFT_FLASH_RIGHT_SOLID = 5,
  MODE_LEFT_SOLID_RIGHT_OFFFF = 6,
  MODE_LEFT_SOLID_RIGHT_FLASH = 7,
  MODE_LEFT_SOLID_RIGHT_SOLID = 8,
}